import type { Metadata } from 'next';
import localFont from 'next/font/local';
import './globals.css';
import Image from 'next/image';
import { Inter } from 'next/font/google';

const cateBold = localFont({
  src: './fonts/CateBold.ttf',
  variable: '--font-cate-bold',
});
const cateBoldItalic = localFont({
  src: './fonts/CateBoldItalic.ttf',
  variable: '--font-cate-bold-italic',
});

const inter = Inter({
  subsets: ['latin'],
  display: 'swap',
  variable: '--font-inter',
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${cateBold.variable} ${cateBoldItalic.variable} ${inter.variable} font-inter antialiased`}>
        <nav className="sticky top-0 left-0 right-0 h-[80px] px-64 flex items-center justify-between bg-black z-50 shadow-[0_0_20px_5px_rgba(0,0,0,0.5)]">
          <a href="/">
            <Image
              src="/images/logo.jpg"
              alt="Top Auto Glass logo"
              width={185}
              height={66}
            />
          </a>
          <div className="flex gap-8 items-center font-cate text-lg">
            <a className="hover:text-glassBlue transition-colors" href="/">
              Home
            </a>
            <a
              className="hover:text-glassBlue transition-colors"
              href="/services">
              Services
            </a>
            <a
              className="hover:text-glassBlue transition-colors"
              href="#contact">
              Contact
            </a>
            <div className="border-2 rounded-md border-glassBlue text-glassBlue hover:text-white hover:border-white transition-colors">
              <a className="px-2 py-1" href="tel:+18327958511">
                (832) 795-8511
              </a>
            </div>
          </div>
        </nav>
        {children}
      </body>
    </html>
  );
}
